"""Declarative base and shared column helpers.

Constraint/index names follow a fixed convention so that hand-written Alembic
migrations, autogenerated migrations and the ORM metadata always agree.
"""
from datetime import datetime, timezone

from sqlalchemy import JSON, MetaData
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase

NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


def utcnow() -> datetime:
    """Timezone-aware 'now' for Python-side defaults."""
    return datetime.now(timezone.utc)


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


# Flexible structured payloads: plain JSON on non-PostgreSQL dialects
# (used for offline/sqlite tests), JSONB on PostgreSQL.
JSONB = JSON().with_variant(JSONB(), "postgresql")
